# Generated by Django 3.1.4 on 2021-01-01 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_todotask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='updated_at',
            field=models.DateTimeField(editable=False),
        ),
    ]
