# Generated by Django 3.1.4 on 2021-01-07 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210101_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='registereduser',
            name='last_name',
        ),
    ]
